name: Deploy Next.js to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/configure-pages@v5
      - name: Install and build
        run: |
          pnpm install
          pnpm run build
      - name: Prepare 404
        run: |
          [ -f out/404.html ] || [ -f out/404/index.html ] || \
          [ -f out/not-found.html ] && cp out/not-found.html out/404.html || \
          echo "<h1>404 - Not Found</h1>" > out/404.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
      - id: deployment
        uses: actions/deploy-pages@v4